// let a ='"asdfsada"';
// let b ="'sadasda'";
// console.log(a,b);
// let c =`hello`;
// console.log(c);
let greeting = 'hello';
let intro = 'my name is Dima';
let msg = greeting+' '+intro;
console.log(msg);
let msg2 = `${greeting} ${intro}`;
console.log(msg2);